global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'prometheus'
    scheme: http
    static_configs:
      - targets: ['prometheus:9090']
  
  - job_name: 'cadvisor'
    scrape_interval: 5s
    file_sd_configs:
      - files:
          - '/etc/prometheus/targets/cadvisor_targets.yml'
        refresh_interval: 5m

  - job_name: 'node_exporter'
    file_sd_configs:
      - files:
          - '/etc/prometheus/targets/node_targets.yml'
        refresh_interval: 5m

  - job_name: 'nginx'
    file_sd_configs:
      - files:
          - '/etc/prometheus/targets/nginx_targets.yml'
        refresh_interval: 5m
  
  - job_name: 'apache'
    file_sd_configs:
      - files:
          - '/etc/prometheus/targets/apache_targets.yml'
        refresh_interval: 5m

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    file_sd_configs:
      - files:
          - '/etc/prometheus/targets/blackbox_targets.yml'
        refresh_interval: 5m
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115