server {
    listen 127.0.0.1:2001;  # Binder explicitement à localhost
    server_name localhost;

    location /stub_status {
        stub_status on;
        allow 127.0.0.1;
        deny all;
        access_log off;
    }
}